project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: slides/slides.ipynb
        text: Slide

format:
  html:
    theme: cosmo
    toc: true
bibliography: reference.bib



